version: "3.5"

services:
  draconiforce_test:
    image: draconiforce-api-test
    build: ./draconiforce-api
    command: npm test
    container_name: draconiforce_test
    restart: on-failure
    external_links:
      - draconiforce_api
    ports:
      - 3002:3002
    volumes:
      - ./draconiforce-api/src:/usr/src/app/src:delegated
      - ./draconiforce-api/dist:/usr/src/app/dist:delegated
      - ./draconiforce-api/circuits:/usr/src/apppp/circuits:delegated
      - ./draconiforce-api/artifacts:/usr/src/app/artifacts:delegated
    networks:
      - draconiforce_backend  

networks:
  draconiforce_backend:
    external: true